remote_theme: just-the-docs/just-the-docs
title: Embracing Digital Transformation
description: Embracing Digital Transformation Podcast Blog Site
logo: "/edt.jpg"
aux_links:
  "Weekly Briefs": "https://www.embracingdigital.org/briefs.html"
  "Podcast Site": "https://soundcloud.com/embracingdigital"
  "Youtube": "https://www.youtube.com/channel/UCveOcNne1kP_ZccC8kOZcDA"
  "LinkedIn Group": "https://linkedin.com/company/embracing-digital-transformation"
  "Facebook Group": "https://www.facebook.com/embracingdigital"
google_analytics: G-SDCPXLJ9YG
