remote_theme: just-the-docs/just-the-docs
title: Embracing Digital Transformation Podcast
tageline: Investigating effective change leveraging people, process, and technology.
description: Which digital trends are a flash in the pan—and which will form the foundations of lasting change? With in-depth discussion and expert interviews, Embracing Digital Transformation finds the signal in the noise of the digital revolution. Embracing Digital Transformation is about bringing people, processes, and technology together for effective digital transformation.
logo: "/edt.jpg"
author: Darren W Pulsipher
aux_links:
  "Weekly Briefs": "https://www.embracingdigital.org/briefs.html"
  "Podcast Site": "https://soundcloud.com/embracingdigital"
  "Youtube": "https://www.youtube.com/channel/UCveOcNne1kP_ZccC8kOZcDA"
  "LinkedIn Group": "https://linkedin.com/company/embracing-digital-transformation"
  "Facebook Group": "https://www.facebook.com/embracingdigital"
google_analytics: G-SDCPXLJ9YG
twitter:
  username: darrenpulsipher
  card: summary
socail:
  name: Darren Pulsipher
  links:
    - https://www.embracingdigital.org/briefs.html
    - https://soundcloud.com/embracingdigital
    - https://www.youtube.com/channel/UCveOcNne1kP_ZccC8kOZcDA
    - https://linkedin.com/company/embracing-digital-transformation
    - https://www.facebook.com/embracingdigital
