remote_theme: just-the-docs/just-the-docs
title: Embracing Digital Transformation Podcast
tagline: Investigating effective change leveraging people, process, and technology.
description: Which digital trends are a flash in the pan—and which will form the foundations of lasting change? With in-depth discussion and expert interviews, Embracing Digital Transformation finds the signal in the noise of the digital revolution. Embracing Digital Transformation is about bringing people, processes, and technology together for effective digital transformation.
languages: ["en", "de", "es", "fr","it","pt", "ja", "ar"]
exclude_from_localizations: ["assets", "CNAME"]
defaultLang: en
languageNames:
  de: Deutsch
  en: English
  es: Español
  fr: Français
  it: Italiano
  pt: Português
  ja: 日本語
  ar: العربية
logo: "./logo.png"
search_enabled: false
author: Darren W Pulsipher
aux_links:
  "Search": "https://embracingdigital.org/search"
  "Shop": "https://6704f0-2.myshopify.com"
  "News Briefs": "https://www.embracingdigital.org/en/briefs.html"
  "Dr Darren Speaks": "https://www.drdarrenspeaks.com"
  "Podcast Site": "https://embracingdigitaltransformation.transistor.fm/"
  "Youtube": "https://www.youtube.com/channel/UCveOcNne1kP_ZccC8kOZcDA?sub_confirmation=1"
  "LinkedIn Group": "https://linkedin.com/company/embracing-digital-transformation"
  "Facebook Group": "https://www.facebook.com/embracingdigital"
google_analytics: G-SDCPXLJ9YG
twitter:
  username: darrenpulsipher
  card: summary
social:
  name: Darren Pulsipher
  links:
    - https://www.embracingdigital.org/briefs.html
    - https://www.youtube.com/channel/UCveOcNne1kP_ZccC8kOZcDA?sub_confirmation=1
    - https://linkedin.com/company/embracing-digital-transformation
    - https://www.facebook.com/embracingdigital
